export enum NodeType {
  PERSON = "PERSON",
  ORGANIZATION = "ORGANIZATION",
  DOCUMENT = "DOCUMENT",
  MESSAGE = "MESSAGE",
  TASK = "TASK",
  TOPIC = "TOPIC",
  CONCEPT = "CONCEPT",
  LOCATION = "LOCATION",
  SYSTEM = "SYSTEM",
}
