export enum RelationshipType {
  MENTIONS = "MENTIONS",
  AUTHORED_BY = "AUTHORED_BY",
  SENT_BY = "SENT_BY",
  REPLIES_TO = "REPLIES_TO",
  PART_OF = "PART_OF",
  REFERENCES = "REFERENCES",
  ASSIGNED_TO = "ASSIGNED_TO",
  INVOLVES = "INVOLVES",
  LOCATED_IN = "LOCATED_IN",
  DERIVED_FROM = "DERIVED_FROM",
  DUPLICATE_OF = "DUPLICATE_OF",
  RELATED_TO = "RELATED_TO",
}
