services:
  postgres:
    image: pgvector/pgvector:pg18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recallos
    volumes:
      - postgres-data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:9.14.0
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@recallos.io
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres

volumes:
  postgres-data:
