services:
  chroma:
    image: chromadb/chroma:1.5.5
    volumes:
      - chroma-data:/data
    ports:
      - "8000:8000"

  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  chroma-data:
  mongo-data:
